modLoader="javafml"
loaderVersion="${mod_loader_version}"
license="All rights reserved"
issueTrackerURL="https://github.com/henkelmax/ultimate-car-mod/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}-SE"
updateJSONURL="https://maxhenkel.de/update/car.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod"
authors="${mod_vendor}, Shin Q'dan (slim enhanced version)"
description='''This mod brings cars and road construction into your Minecraft world. Slimmed down from fuel production functionality provided in other mods and enhanced by more advanced car behavior (acceleration, max speed, etc) logic. Special thanks to KlaraAga.'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${mod_forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod_minecraft_version}]"
    ordering="NONE"
    side="BOTH"